name: Build for Windows
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: Install dependencies
        run: |
          go get .
          go install github.com/fyne-io/fyne-cross@latest

      - name: Package for Windows
        run: fyne-cross version && fyne-cross windows -arch=amd64 -app-id=pinpox.tmx.uploader -debug --no-cache .
        # run: fyne-cross windows -arch=amd64 && mkdir -p pkg && mv fyne-cross/bin/windows-amd64/Anarchy-Droid.exe pkg/Anarchy-Droid_windows_amd64.exe && mv fyne-cross/dist/windows-amd64/Anarchy-Droid.exe.zip pkg/Anarchy-Droid.zip
    
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: Anarchy-Droid (Windows)
    #     path: pkg

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: Anarchy-Droid_windows_amd64.exe
    #     path: pkg/Anarchy-Droid_windows_amd64.exe
